/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import { Scene } from "laya/display/Scene";
import { ClassUtils } from "laya/utils/ClassUtils";
var REG: Function = ClassUtils.regClass;
import { Label } from "laya/ui/Label";
import { Button } from "laya/ui/Button";
import { Dialog } from "laya/ui/Dialog";
import { Box } from "laya/ui/Box";
import { Sprite } from "laya/display/Sprite";
import { Image } from "laya/ui/Image";
import { ProgressBar } from "laya/ui/ProgressBar";
export module ui.pop.alert {
    export class alertUI extends Dialog {
		public label:Label;
		public btn_cancel:Button;
		public btn_confirm:Button;
        public referenceClass:Array<any>=[Label, Button, Dialog, Box, Sprite, 
				Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/alert/alert");
        }
    }
    REG("ui.pop.alert.alertUI",alertUI);
    export class buyBulletUI extends Dialog {
		public btn_minus:Button;
		public btn_add:Button;
		public cost_num:Label;
		public btn_buy:Button;
        public referenceClass:Array<any>=[Button, Label, Dialog, Box, Sprite, 
				Image]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/alert/buyBullet");
        }
    }
    REG("ui.pop.alert.buyBulletUI",buyBulletUI);
    export class tipUI extends Dialog {
		public bg:Image;
		public label:Label;
        public referenceClass:Array<any>=[Image, Label, Dialog]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/alert/tip");
        }
    }
    REG("ui.pop.alert.tipUI",tipUI);
    export class topTipUI extends Dialog {
		public bg:Image;
		public label:Label;
        public referenceClass:Array<any>=[Image, Label, Dialog]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/alert/topTip");
        }
    }
    REG("ui.pop.alert.topTipUI",topTipUI);
    export class voiceUI extends Dialog {
		public music_progress:ui.pop.alert.voiceProgressUI;
		public voice_progress:ui.pop.alert.voiceProgressUI;
        public referenceClass:Array<any>=[Dialog, Box, Sprite, Image, Button, 
				]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/alert/voice");
        }
    }
    REG("ui.pop.alert.voiceUI",voiceUI);
    export class voiceProgressUI extends Scene {
		public progress_bar:ProgressBar;
		public progress_btn:Button;
        public referenceClass:Array<any>=[ProgressBar, Button, Box]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/alert/voiceProgress");
        }
    }
    REG("ui.pop.alert.voiceProgressUI",voiceProgressUI);
}
export module ui.pop {
    export class helpUI extends Dialog {
		public title:Sprite;
        public referenceClass:Array<any>=[Sprite, Dialog, Image, Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/help");
        }
    }
    REG("ui.pop.helpUI",helpUI);
}
import { View } from "laya/ui/View";
import { List } from "laya/ui/List";
export module ui.pop.lottery {
    export class itemUI extends View {
		public light:Sprite;
		public bullet_num:Label;
		public cur_light:Sprite;
		public bullet_icon:Sprite;
		public item_num:Label;
		public item_type:Label;
        public referenceClass:Array<any>=[Sprite, Label, View]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/lottery/item");
        }
    }
    REG("ui.pop.lottery.itemUI",itemUI);
    export class item2UI extends Scene {
		public btn_buy:Button;
		public price_label:Label;
		public price_tag:Image;
		public remain_label:Label;
		public num_label:Label;
		public type_label:Label;
        public referenceClass:Array<any>=[Button, Label, Image, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/lottery/item2");
        }
    }
    REG("ui.pop.lottery.item2UI",item2UI);
    export class lotteryUI extends Dialog {
		public bg:Box;
		public title:Image;
		public lottery_list:List;
		public btn_lottery:Button;
		public progress:ProgressBar;
		public lottery_remain:Label;
		public exchange_list:List;
        public referenceClass:Array<any>=[Box, Image, List, Button, ProgressBar, 
				Label, Dialog, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/lottery/lottery");
        }
    }
    REG("ui.pop.lottery.lotteryUI",lotteryUI);
}
import { ViewStack } from "laya/ui/ViewStack";
export module ui.pop.shop {
    export class shopUI extends Dialog {
		public bg:Box;
		public title:Image;
		public gun_list:List;
		public item_list:List;
        public referenceClass:Array<any>=[Box, Image, List, Dialog, Sprite, 
				Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/shop/shop");
        }
    }
    REG("ui.pop.shop.shopUI",shopUI);
    export class shopGunItemUI extends Scene {
		public bg:Sprite;
		public icon:Image;
		public name_label:Label;
		public stack_btn:ViewStack;
        public referenceClass:Array<any>=[Sprite, Image, Label, ViewStack, Button, 
				]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/shop/shopGunItem");
        }
    }
    REG("ui.pop.shop.shopGunItemUI",shopGunItemUI);
    export class shopItemItemUI extends Scene {
		public bg:Sprite;
		public icon:Image;
		public num_label:Label;
		public name_label:Label;
		public btn_buy:Button;
		public price_label:Label;
        public referenceClass:Array<any>=[Sprite, Image, Label, Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("pop/shop/shopItemItem");
        }
    }
    REG("ui.pop.shop.shopItemItemUI",shopItemItemUI);
}
import { HTMLDivElement } from "laya/html/dom/HTMLDivElement";
import { Skeleton } from "laya/ani/bone/Skeleton";
export module ui.scenes.game {
    export class gameUI extends Scene {
		public bg:Box;
		public pool:Box;
		public ani_wrap:Box;
		public ctrl_box:Box;
		public btn_leave:Button;
		public btn_gift:Button;
		public btn_voice:Button;
		public btn_help:Button;
		public skill_box:ui.scenes.game.skillBoxUI;
		public bullet_box:Box;
		public bullet_box_bg:Image;
		public bullet_num:Label;
		public exchange_rate:HTMLDivElement;
		public gun_wrap:Box;
		public btn_shop:Button;
        public referenceClass:Array<any>=[Box, Button, Image, Label, HTMLDivElement, 
				]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/game/game");
        }
    }
    REG("ui.scenes.game.gameUI",gameUI);
    export class gunBoxUI extends View {
		public ani_box:Box;
		public gun_box:Box;
		public base:Skeleton;
		public gun:Skeleton;
		public light:Skeleton;
		public body:Skeleton;
		public ctrl_box:Sprite;
		public score_box:Image;
		public score_label:Label;
		public btn_minus:Button;
		public btn_add:Button;
        public static  uiView:any ={"type":"View","props":{"y":111,"x":111,"width":223,"runtime":"view/scenes/game/gunBoxView.ts","mouseThrough":true,"mouseEnabled":true,"height":223,"anchorY":0.5,"anchorX":0.5},"compId":2,"child":[{"type":"Box","props":{"y":114,"x":111,"width":149,"var":"ani_box","pivotY":77.5,"pivotX":74,"height":149},"compId":7,"child":[{"type":"Box","props":{"y":77.5,"x":74,"width":59,"var":"gun_box","height":45},"compId":8,"child":[{"type":"SkeletonPlayer","props":{"var":"base","url":"ani/gun/base11.sk","runtime":"laya.ani.bone.Skeleton"},"compId":9},{"type":"SkeletonPlayer","props":{"var":"gun","url":"ani/gun/gun11.sk","runtime":"laya.ani.bone.Skeleton"},"compId":10},{"type":"SkeletonPlayer","props":{"y":0,"x":0,"var":"light","url":"ani/gun/light11.sk","runtime":"laya.ani.bone.Skeleton"},"compId":11},{"type":"SkeletonPlayer","props":{"y":0,"x":0,"var":"body","url":"ani/gun/light11.sk","runtime":"laya.ani.bone.Skeleton"},"compId":18}]}]},{"type":"Sprite","props":{"y":111.5,"x":-2,"visible":false,"var":"ctrl_box"},"compId":17,"child":[{"type":"Image","props":{"y":27,"x":113,"width":150,"var":"score_box","skin":"image/game/time_bg.png","sizeGrid":"0,20,0,22","height":48,"anchorY":0.5,"anchorX":0.5},"compId":13,"child":[{"type":"Label","props":{"y":2,"x":13,"width":124,"var":"score_label","valign":"middle","height":44,"font":"score_num","align":"center"},"compId":14}]},{"type":"Button","props":{"y":1,"var":"btn_minus","stateNum":1,"skin":"image/game/btn_minus.png","left":22},"compId":16},{"type":"Button","props":{"y":1,"x":153,"var":"btn_add","stateNum":1,"skin":"image/game/btn_add.png"},"compId":15}]}],"loadList":["ani/gun/base11.sk","ani/gun/gun11.sk","ani/gun/light11.sk","image/game/time_bg.png","image/game/btn_minus.png","image/game/btn_add.png"],"loadList3D":[]};
        public referenceClass:Array<any>=[Box, Skeleton, Sprite, Image, Label, 
				Button, View]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(gunBoxUI.uiView);
        }
    }
    REG("ui.scenes.game.gunBoxUI",gunBoxUI);
    export class skillBoxUI extends View {
		public energy_bar:Sprite;
		public skill_list:Box;
		public auto_launch:Sprite;
		public energy_light:Skeleton;
        public referenceClass:Array<any>=[Sprite, Box, Skeleton, View]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/game/skillBox");
        }
    }
    REG("ui.scenes.game.skillBoxUI",skillBoxUI);
    export class skillItemUI extends View {
		public skill_icon:Image;
		public overlay:Sprite;
		public num_label:Label;
		public border_light:Skeleton;
        public static  uiView:any ={"type":"View","props":{"width":94,"runtime":"view/scenes/game/skillItemView.ts","mouseThrough":false,"mouseEnabled":true,"height":96},"compId":2,"child":[{"type":"Sprite","props":{"y":48,"x":47,"width":94,"texture":"image/game/skill_bg.png","pivotY":48,"pivotX":47,"height":96},"compId":3},{"type":"Image","props":{"y":7,"x":8,"width":80,"var":"skill_icon","skin":"image/game/skill_aim.png","height":80},"compId":7},{"type":"Sprite","props":{"y":8,"x":8,"width":81,"var":"overlay","texture":"image/game/skill_overlay.png","height":79},"compId":6},{"type":"Label","props":{"y":59,"x":8,"width":78,"var":"num_label","valign":"middle","text":"200","strokeColor":"#000","stroke":2,"height":28,"fontSize":20,"color":"#ffffff","align":"right"},"compId":5},{"type":"SkeletonPlayer","props":{"y":48,"x":48.5,"visible":false,"var":"border_light","url":"ani/other/skill_border_light.sk","runtime":"laya.ani.bone.Skeleton"},"compId":8}],"loadList":["image/game/skill_bg.png","image/game/skill_aim.png","image/game/skill_overlay.png","ani/other/skill_border_light.sk"],"loadList3D":[]};
        public referenceClass:Array<any>=[Image, Sprite, Label, Skeleton, View, 
				]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(skillItemUI.uiView);
        }
    }
    REG("ui.scenes.game.skillItemUI",skillItemUI);
}
export module ui.scenes.hall {
    export class coinMenuUI extends View {
		public bg:Image;
		public list:List;
        public referenceClass:Array<any>=[Image, List, View, Sprite, Box, 
				Label]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/hall/coinMenu");
        }
    }
    REG("ui.scenes.hall.coinMenuUI",coinMenuUI);
    export class flagMenuUI extends View {
		public bg:Image;
		public list:List;
        public referenceClass:Array<any>=[Image, List, View, Sprite, Box, 
				]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/hall/flagMenu");
        }
    }
    REG("ui.scenes.hall.flagMenuUI",flagMenuUI);
    export class hallUI extends Scene {
		public bg:Sprite;
		public normal_box:Box;
		public match_box:Box;
		public mermaid:Skeleton;
		public header:ui.scenes.hall.headerUI;
		public btn_play_now:Box;
        public referenceClass:Array<any>=[Sprite, Box, Skeleton, Label]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/hall/hall");
        }
    }
    REG("ui.scenes.hall.hallUI",hallUI);
    export class headerUI extends View {
		public user_box:Box;
		public nickname:Label;
		public coin_menu:ui.scenes.hall.coinMenuUI;
		public btn_coin_select:Box;
		public coin_name:Label;
		public coin_num:Label;
		public coin_icon:Image;
		public btn_charge:Button;
		public btn_get:Button;
		public btn_home:Button;
		public btn_app:Button;
		public btn_leave:Button;
		public btn_voice:Button;
		public btn_login:Button;
		public flag_menu:ui.scenes.hall.flagMenuUI;
		public flag_box:Box;
		public flag:Image;
        public referenceClass:Array<any>=[Box, Label, Image, Button, View, 
				Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/hall/header");
        }
    }
    REG("ui.scenes.hall.headerUI",headerUI);
}
export module ui.scenes {
    export class loadingUI extends Dialog {
		public progress:ProgressBar;
        public referenceClass:Array<any>=[ProgressBar, Dialog, Sprite]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/loading");
        }
    }
    REG("ui.scenes.loadingUI",loadingUI);
    export class startUI extends Scene {
		public btn_back:Button;
        public referenceClass:Array<any>=[Button]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/start");
        }
    }
    REG("ui.scenes.startUI",startUI);
    export class testUI extends Scene {
        public referenceClass:Array<any>=[Box]; // 强制引用类,防止被编译器忽略
		constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("scenes/test");
        }
    }
    REG("ui.scenes.testUI",testUI);
}