/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import tip from "./view/pop/tip"
import topTip from "./view/pop/topTip"
import shop from "./view/pop/shop"
import gameView from "./view/scenes/game/gameView"
import gunBoxView from "./view/scenes/game/gunBoxView"
import skillItemView from "./view/scenes/game/skillItemView"
import hallView from "./view/scenes/hallView"
import loadingView from "./view/scenes/loadingView"
import startView from "./view/scenes/startView"
import { Templet } from "laya/ani/bone/Templet"
import { HTMLDivElement } from "laya/html/dom/HTMLDivElement"
import { ClassUtils } from "laya/utils/ClassUtils";
import { ui } from "./ui/layaMaxUI";
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=750;
    static scaleMode:string="fixedheight";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="pop/alert/alert.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = ClassUtils.regClass;
		reg("ui", ui);
        reg("view/pop/tip.ts",tip);
        reg("view/pop/topTip.ts",topTip);
        reg("view/pop/shop.ts",shop);
        reg("view/scenes/game/gameView.ts",gameView);
        reg("view/scenes/game/gunBoxView.ts",gunBoxView);
        reg("view/scenes/game/skillItemView.ts",skillItemView);
        reg("view/scenes/hallView.ts",hallView);
        reg("view/scenes/loadingView.ts",loadingView);
        reg("view/scenes/startView.ts",startView);
        reg("laya.ani.bone.Templet",Templet);
        reg("laya.html.dom.HTMLDivElement",HTMLDivElement);
    }
}
GameConfig.init();